export const columnDefs = [
  { headerName: 'Row ID', field: 'row_id', width: 220 },
  { headerName: 'Network ID', field: 'network_id', width: 220 },
  { headerName: 'Code', field: 'code' },
  { headerName: 'Original Code', field: 'original_code' },
  {
    headerName: 'Rate',
    field: 'rate',
    type: 'numericColumn',
  },
  {
    headerName: 'MRF Rate',
    field: 'mrf_rate',
    type: 'numericColumn',
  },
  { headerName: 'EIN', field: 'ein' },
  { headerName: 'NPI List', field: 'npi_list' },
  { headerName: 'Source Group ID', field: 'source_group_id' },
  { headerName: 'Group ID', field: 'group_id' },
  { headerName: 'NPI Region', field: 'npi_region' },
  { headerName: 'NPI Taxonomy', field: 'npi_taxonomy' },
  { headerName: 'Code Type', field: 'code_type' },
  { headerName: 'Original Code Type', field: 'original_code_type' },
  { headerName: 'Code Type Version', field: 'code_type_version' },
  { headerName: 'Modifier List', field: 'modifier_list' },
  { headerName: 'Bundled Code List', field: 'bundled_code_list' },
  { headerName: 'Billing Class', field: 'billing_class' },
  { headerName: 'Place of Service List', field: 'place_of_service_list' },
  { headerName: 'Negotiation Type', field: 'negotiation_type' },
  { headerName: 'Arrangement', field: 'arrangement' },
  { headerName: 'CMS Baseline Schedule', field: 'cms_baseline_schedule' },
  {
    headerName: 'CMS Baseline Rate',
    field: 'cms_baseline_rate',
  },
  { headerName: 'Expiration', field: 'expiration' },
  { headerName: 'Additional Info', field: 'additional_information' },
  { headerName: 'Billable Primary Taxonomy', field: 'is_billable_primary_taxonomy' },
  { headerName: 'Billable Secondary Taxonomy', field: 'is_billable_secondary_taxonomy' },
  { headerName: 'Billable Claims', field: 'is_billable_claims' },
  { headerName: 'Is Imputed', field: 'is_imputed' },
  { headerName: 'Anesthesia Base Units', field: 'anesthesia_base_units' },
  { headerName: 'Anesthesia Time Unit', field: 'anesthesia_time_unit' },
  { headerName: 'Anesthesia Conversion Rate', field: 'anesthesia_conversion_rate' },
  { headerName: 'Anesthesia Estimated $', field: 'anesthesia_estimated_dollar_amount' },
  {
    headerName: 'Anesthesia Conversion Factor Methodology',
    field: 'anesthesia_conversion_factor_methodology',
  },
  {
    headerName: 'Relative to Baseline',
    field: 'relative_to_baseline',
  },
  { headerName: 'NPI List Length', field: 'npi_list_length' },
  { headerName: 'NPI Geo', field: 'npiGeo' },
  { headerName: 'CBSAs', field: 'cbsas' },
  { headerName: 'Place of Service', field: 'place_of_service' },
  { headerName: 'Entity Name', field: 'entity_name', pinned: 'left' as const, width: 200 },
  { headerName: 'Entity Address', field: 'entity_address' },
  { headerName: 'Matched On', field: 'matched_on' },
  { headerName: 'Matched ID', field: 'matched_id' },
  { headerName: 'Network Name', field: 'network_name' },
  { headerName: 'Network Region', field: 'network_region' },
  { headerName: 'Network Year-Month', field: 'network_year_month' },
  { headerName: 'Date Accessed', field: 'date_accessed' },
  { headerName: 'Payer Name', field: 'payer_name' },
  { headerName: 'NPI Taxonomy Name', field: 'npi_taxonomy_name' },
  { headerName: 'Network Template ID', field: 'network_template_id' },
  { headerName: 'Baseline Schedule', field: 'baseline_schedule' },
  {
    headerName: 'Baseline Rate',
    field: 'baseline_rate',
  },
  { headerName: 'Baseline Original', field: 'baseline_original' },
  { headerName: 'Baseline Original Type', field: 'baseline_original_type' },
]
